//
//  Constants.swift
//  DoctorNearby
//
//  Created by Vince Zhang on 2015-09-25.
//  Copyright © 2015 AkhalTech. All rights reserved.
//

import Foundation

class City: NSObject {
    
    class func names(province: String) -> Array <String> {
        if province == "Alberta" {
            return ["ALL"]
        }else if province == "British Columbia" {
            return britishColumbiaNames
        }else if province == "Manitoba" {
            return ["ALL"]
        }else if province == "New Brunswick" {
            return ["ALL"]
        }else if province == "Newfoundland and Labrador" {
            return ["ALL"]
        }else if province == "Nova Scotia" {
            return ["ALL"]
        }else if province == "Northwest Territories" {
            return ["ALL"]
        }else if province == "Nunavut" {
            return ["ALL"]
        }else if province == "Ontario" {
            return ontarioNames
        }else if province == "Prince Edward Island" {
            return ["ALL"]
        }else if province == "Quebec" {
            return quebecNames
        }else if province == "Saskatchewan" {
            return ["ALL"]
        }else if province == "Yukon" {
            return ["ALL"]
        }else {
            return ["ALL"]
        }
    }
    
    static let quebecNames = [
        "ALL",
        "Abercorn",
        "Adstock",
        "Agathe-des-Monts",
        "Akwesasne",
        "Albanel",
        "Alma",
        "Alouette",
        "Amos",
        "Amqui",
        "Ange-Gardien",
        "Angus",
        "Anjou",
        "Armagh",
        "Asbestos",
        "Austin",
        "Baie",
        "Baie-Comeau",
        "Baie-James",
        "Baie-Saint-Paul",
        "Baie-d'Urfé",
        "Bassin",
        "Bay",
        "Beaconsfield",
        "Beauce",
        "Beauce-Sud",
        "Beauceville",
        "Beauharnois",
        "Beaumont",
        "Beauport",
        "Beaupré",
        "Bedford",
        "Beloeil",
        "Bergeronnes",
        "Berthier-sur-Mer",
        "Berthierville",
        "Blainville",
        "Blanc-Sablon",
        "Bois-des-Filion",
        "Boisbriand",
        "Boischatel",
        "Bolton",
        "Bolton-Ouest",
        "Bonaventure",
        "Borromée",
        "Boucherville",
        "Brigham",
        "Brome",
        "Bromont",
        "Brossard",
        "Broughton",
        "Brownsburg-Chatham",
        "Buckingham",
        "Bukcingham",
        "Bécancour",
        "Cacouna",
        "Canada",
        "Candiac",
        "Cantley",
        "Cap-Aux-Meules",
        "Cap-Chat",
        "Cap-Saint-Ignace",
        "Cap-Santé",
        "Cap-aux-Meules",
        "Cap-aux-meules",
        "Caplan",
        "Carignan",
        "Carleton",
        "Carleton-sur-Mer",
        "Carré",
        "Chambly",
        "Chambord",
        "Chandler",
        "Chapais",
        "Charlemagne",
        "Charlesbourg",
        "Charny",
        "Chateauguay",
        "Chelsea",
        "Chertsey",
        "Chibougamau",
        "Chicoutimi",
        "Chisasibi",
        "Chomedey-Laval",
        "Chrysostome",
        "Château-Richer",
        "Châteaugauy",
        "Châteaugay",
        "Châteauguay",
        "Chénéville",
        "Claire",
        "Clermont",
        "Coaticook",
        "Comeau",
        "Contrecoeur",
        "Cookshire",
        "Cookshire-Eaton",
        "Coteau-du-Lac",
        "Coudres",
        "Courcelette",
        "Courcelettes",
        "Courcelles",
        "Cowansville",
        "Cèdres",
        "Côte-Saint-Luc",
        "Côteau-du-Lac",
        "Côteaux",
        "D'Espoir",
        "Danville",
        "Delson",
        "Deschaillons-sur-Saint-Laurent",
        "Deschambault",
        "Desmaures",
        "Deux-Montagnes",
        "Disraeli",
        "Disraéli",
        "Dolbeau",
        "Dolbeau-Mistassini",
        "Dollard-des-Ormeaux",
        "Donnacona",
        "Donnaconna",
        "Dorval",
        "Drummondvile",
        "Drummondville",
        "Drummonville",
        "Duhamel-Ouest",
        "Dunham",
        "Dégelis",
        "East",
        "Eastman",
        "Entrelacs",
        "Escoumins",
        "Essipit",
        "Eustache",
        "Falls",
        "Farhnam",
        "Farnham",
        "Ferme-Neuve",
        "Fermont",
        "Filion",
        "Fleurimont",
        "Forest",
        "Forestville",
        "Fort-Coulonge",
        "Fortierville",
        "Foster",
        "Frontenac",
        "Gardeur",
        "Gartineau",
        "Gaspé",
        "Gatineau",
        "Gore",
        "Gracefield",
        "Granby",
        "Grand-Mère",
        "Grande-Rivière",
        "Grande-Vallée",
        "Greenfieldpark",
        "Grenville-sur-la-Rouge",
        "Guadeloupe",
        "Ham-Nord",
        "Hampstead",
        "Hatley",
        "Havre-Saint-Pierre",
        "Hebertville",
        "Henryville",
        "Huberdeau",
        "Hudson",
        "Hull",
        "Huntingdon",
        "Hébertville",
        "Ile-des-Soeurs",
        "Iles-de-la-Madeleine",
        "Inukjuak",
        "Joliette",
        "Jonquiere",
        "Jonquière",
        "Jérôme",
        "Kahnawake",
        "Kamouraska",
        "Kanesatake",
        "Kawawachikamach",
        "Kirkland",
        "Knowlton",
        "Kuujjuaq",
        "Kuujuuaq",
        "L'Ancienne-Lorette",
        "L'Ange-Gardien",
        "L'Anse-Saint-Jean",
        "L'Assomption",
        "L'Epiphanie",
        "L'Ile-Bizard",
        "L'Islet",
        "L'Isletville",
        "L'ancienne-Lorette",
        "L'Épiphanie",
        "L'Île-Bizard",
        "L'Île-Perrot",
        "LAVAL",
        "LaSalle",
        "Labelle",
        "Lac",
        "Lac-Beauport",
        "Lac-Bouchette",
        "Lac-Brome",
        "Lac-Drolet",
        "Lac-Etchemin",
        "Lac-Kénogami",
        "Lac-Megantic",
        "Lac-Mégantic",
        "Lac-Saint-Jean",
        "Lac-Saint-Joseph",
        "Lac-Supérieur",
        "Lac-des-Aigles",
        "Lachenaie",
        "Lachine",
        "Lachute",
        "Lacolle",
        "Ladysmith",
        "Lafontaine",
        "Lake",
        "Lambert",
        "Lanoraie",
        "Laplaine",
        "Laprairie",
        "Lasalle",
        "Laterriere",
        "Laterrière",
        "Latuque",
        "Laurent",
        "Laurier-Station",
        "Lauzon",
        "Laval",
        "Lavaltrie",
        "Lebel-sur-Quevillon",
        "Lebel-sur-Quévillon",
        "Lemoyne",
        "Lennoxville",
        "Levis",
        "Longueuil",
        "Loretteville",
        "Lorraine",
        "Lotbiniere",
        "Louiseville",
        "Loup",
        "Lourdes-de-Blanc-Sablon",
        "Luc",
        "Lyster",
        "Léry",
        "Lévis",
        "MONTREAL",
        "MONTRÉAL",
        "Macaza",
        "Magog",
        "Malartic",
        "Malbaie",
        "Maniwaki",
        "Mansfield",
        "Mansfield-Pontefract",
        "Mansonville",
        "Maria",
        "Marie",
        "Marieville",
        "Mascouche",
        "Mashteuiatsh",
        "Maskinongé",
        "Matagami",
        "Matane",
        "Matapedia",
        "Matapédia",
        "McMasterville",
        "Mercier",
        "Mille-Isles",
        "Minerve",
        "Mines",
        "Mirabel",
        "Misstissini",
        "Mistissini",
        "Mont-Joli",
        "Mont-Laurier",
        "Mont-Royal",
        "Mont-Saint-Hilaire",
        "Mont-Tremblant",
        "Mont-Wright",
        "Montarville",
        "Montcalm",
        "Montmagny",
        "Montpellier",
        "Montreal",
        "Montrèal",
        "Montréal",
        "Montréal-Est",
        "Montréal-Nord",
        "Montréal-Ouest",
        "Montréal-ouest",
        "Monts",
        "Morin",
        "Morin-Heights",
        "Murdochville",
        "Mégantic",
        "Métabetchouan-Lac-A-La-Croix",
        "Métabetchouan-Lac-à-la-Croix",
        "Napierville",
        "Neuville",
        "Nicolet",
        "Nominingue",
        "Noranda",
        "Normandin",
        "North-Hatley",
        "Notre-Dame-Du-Lac",
        "Notre-Dame-de-L'Île-Perrot",
        "Notre-Dame-de-l'Île-Perrot",
        "Notre-Dame-de-la-Merci",
        "Notre-Dame-des-Prairies",
        "Notre-Dame-du-Lac",
        "Notre-Dame-du-Mont-Carmel",
        "Notre-Dame-du-Portage",
        "Nunavik",
        "Némaska",
        "Ogden",
        "Oka",
        "Orford",
        "Ormstown",
        "Ottawa",
        "Outremont",
        "Outrermont",
        "Papineauville",
        "Park",
        "Paspebiac",
        "Paspébiac",
        "Patrie",
        "Paul",
        "Percé",
        "Perrot",
        "Piedmont",
        "Pierrefond",
        "Pierrefonds",
        "Pierreville",
        "Pincourt",
        "Plaine",
        "Plaisance",
        "Plessisville",
        "Pocatière",
        "Pohénégamook",
        "Pointe-CLaire",
        "Pointe-Claire",
        "Pointe-au-Père",
        "Pointe-aux-Trembles",
        "Pointe-claire",
        "Pointe-des-Cascades",
        "Pointe-à-La-Croix",
        "Pointe-à-la-Croix",
        "Pond",
        "Pont-Rouge",
        "Port-Cartier",
        "Portneuf",
        "Potton",
        "Prairie",
        "Preissac",
        "Princeville",
        "Prévost",
        "Puvirnituq",
        "Quebec",
        "Quyon",
        "Québec",
        "Radisson",
        "Rawdon",
        "Repentigny",
        "Richelain",
        "Richelieu",
        "Richmond",
        "Rigaud",
        "Rimouski",
        "Ripon",
        "Rive",
        "Riviere-du-Loup",
        "Rivière-Beaudette",
        "Rivière-Bleue",
        "Rivière-Du-Loup",
        "Rivière-Rouge",
        "Rivière-au-Renard",
        "Rivière-du-Loup",
        "Rivière-du-loup",
        "Roberval",
        "Rosemère",
        "Rouge",
        "Rougemont",
        "Rouyn-Noranda",
        "Roxboro",
        "Royal",
        "Ruisseaux",
        "Répentigny",
        "SOREL-TRACY",
        "Sablon",
        "Sacré-Coeur",
        "Saguenay",
        "Saint-Adolphe-D'Howard",
        "Saint-Adolphe-d'Howard",
        "Saint-Agapit",
        "Saint-Agathe-des-Monts",
        "Saint-Alexandre-de-Kamouraska",
        "Saint-Alexis",
        "Saint-Alexis-des-Monts",
        "Saint-Alphonse-Rodriguez",
        "Saint-Amable",
        "Saint-Ambroise-de-Kildare",
        "Saint-André-Avellin",
        "Saint-André-d'Argenteuil",
        "Saint-Anne-des-Monts",
        "Saint-Anselme",
        "Saint-Antoine-de-Lavaltrie",
        "Saint-Apollinaire",
        "Saint-Aubert",
        "Saint-Augustin-de-Desmaures",
        "Saint-Barthélémy",
        "Saint-Basile",
        "Saint-Basile-le-Grand",
        "Saint-Benjamin",
        "Saint-Benoît-Labre",
        "Saint-Bernard",
        "Saint-Boniface",
        "Saint-Boniface-de-Shawinigan",
        "Saint-Bruno",
        "Saint-Bruno-de-Montarville",
        "Saint-Calixte",
        "Saint-Casimir",
        "Saint-Cesaire",
        "Saint-Charles-Boromée",
        "Saint-Charles-Borromee",
        "Saint-Charles-Borromé",
        "Saint-Charles-Borromée",
        "Saint-Charles-de-Bellechasse",
        "Saint-Christophe-d'Arthabaska",
        "Saint-Chrysostome",
        "Saint-Colomban",
        "Saint-Constant",
        "Saint-Cuthbert",
        "Saint-Cyrille-de-Wendover",
        "Saint-Césaire",
        "Saint-Côme",
        "Saint-Côme-Linière",
        "Saint-Damase",
        "Saint-Damien-de-Buckland",
        "Saint-David",
        "Saint-Denis-Sur-Richelieu",
        "Saint-Denis-de-Brompton",
        "Saint-Denis-sur-Richelieu",
        "Saint-Donat",
        "Saint-Donat-de-Montcalm",
        "Saint-Ephrem-de-Beauce",
        "Saint-Esprit",
        "Saint-Etienne-de-Lauzon",
        "Saint-Etienne-des-Grès",
        "Saint-Eustache",
        "Saint-Fabien",
        "Saint-Fabien-de-Panet",
        "Saint-Ferréol-les-Neiges",
        "Saint-François-d'Orléans",
        "Saint-François-de-la-Rivière-du-Sud",
        "Saint-Félicien",
        "Saint-Félix-de-Valois",
        "Saint-Gabriel",
        "Saint-Gabriel-de-Brandon",
        "Saint-Georges",
        "Saint-Georges-de-Beauce",
        "Saint-Georges-de-Windsor",
        "Saint-Germain-de-Grantham",
        "Saint-Grégoire",
        "Saint-Gédéon",
        "Saint-Gédéon-de-Beauce",
        "Saint-Henri-de-Lévis",
        "Saint-Hippolyte",
        "Saint-Honoré-de-Chicoutimi",
        "Saint-Hubert",
        "Saint-Hubert-Rivière-du-Loup",
        "Saint-Hyacinthe",
        "Saint-Hyacynthe",
        "Saint-Hyancinthe",
        "Saint-Ignace-de-Loyola",
        "Saint-Irénée",
        "Saint-Isidore",
        "Saint-Jacques",
        "Saint-Jacques-de-Leeds",
        "Saint-Jean",
        "Saint-Jean-Chrisostome",
        "Saint-Jean-Chrysostome",
        "Saint-Jean-Chrysostôme",
        "Saint-Jean-D'Orléans",
        "Saint-Jean-Port-Joli",
        "Saint-Jean-Sur-Richelieu",
        "Saint-Jean-d'Orléans",
        "Saint-Jean-de-Matha",
        "Saint-Jean-des-Piles",
        "Saint-Jean-sur-Richelieu",
        "Saint-Jean-sur-le-Richelieu",
        "Saint-Jerôme",
        "Saint-Joseph",
        "Saint-Joseph-de-Beauce",
        "Saint-Joseph-de-Coleraine",
        "Saint-Joseph-de-Lepage",
        "Saint-Joseph-du-Lac",
        "Saint-Jérome",
        "Saint-Jérôme",
        "Saint-Lambert",
        "Saint-Lambert-de-Lauzon",
        "Saint-Laurent",
        "Saint-Laurent-de-l'Île-d'Orléans",
        "Saint-Lazare",
        "Saint-Leonard",
        "Saint-Liboire",
        "Saint-Liguori",
        "Saint-Lin-Laurentides",
        "Saint-Luc",
        "Saint-Léonard",
        "Saint-Léonard-d'Aston",
        "Saint-Marc-des-Carrières",
        "Saint-Marc-sur-Richelieu",
        "Saint-Martin",
        "Saint-Mathias-sur-Richelieu",
        "Saint-Mathieu-de-Beloeil",
        "Saint-Maurice",
        "Saint-Michel-de-Bellechasse",
        "Saint-Michel-des-Saints",
        "Saint-Narcisse-de-Rimouski",
        "Saint-Nazaire",
        "Saint-Nazaire-du-Lac-Saint-Jean",
        "Saint-Nicephore",
        "Saint-Nicolas",
        "Saint-Nicéphore",
        "Saint-Nérée",
        "Saint-Omer",
        "Saint-Ours",
        "Saint-Pamphile",
        "Saint-Pascal",
        "Saint-Patrice-de-Beaurivage",
        "Saint-Paul",
        "Saint-Paul-de-Joliette",
        "Saint-Paulin",
        "Saint-Philippe",
        "Saint-Pie",
        "Saint-Pierre",
        "Saint-Pierre-Les-Becquets",
        "Saint-Pierre-de-l'Île-d'Orléans",
        "Saint-Polycarpe",
        "Saint-Prime",
        "Saint-Prosper",
        "Saint-Prosper-de-Dorchester",
        "Saint-Raphael",
        "Saint-Raymond",
        "Saint-Raymond-de-Portneuf",
        "Saint-Roch-de-l'Achigan",
        "Saint-Roch-des-Aulnaies",
        "Saint-Romain",
        "Saint-Romuald",
        "Saint-Rédempteur",
        "Saint-Rémi",
        "Saint-Sauveur",
        "Saint-Sauveur-des-Monts",
        "Saint-Siméon",
        "Saint-Stanislas",
        "Saint-Stanislas-de-Champlain",
        "Saint-Stanislas-de-Kostka",
        "Saint-Sébastien",
        "Saint-Thomas",
        "Saint-Tite",
        "Saint-Ubalde",
        "Saint-Vallier",
        "Saint-Valérien",
        "Saint-Wenceslas",
        "Saint-Zacharie",
        "Saint-Zotique",
        "Saint-eustache",
        "Saint-Élie-d'Orford",
        "Saint-Épiphane",
        "Saint-Étienne-de-Bolton",
        "Saint-Étienne-de-Lauzon",
        "Saint-Étienne-des-Grès",
        "Saint-Étienne-des-Grés",
        "Sainte-Adele",
        "Sainte-Adèle",
        "Sainte-Agathe",
        "Sainte-Agathe-Des-Monts",
        "Sainte-Agathe-de-Lotbinière",
        "Sainte-Agathe-des-Monts",
        "Sainte-Agathe-des-monts",
        "Sainte-Anne-Des-Monts",
        "Sainte-Anne-Du-Sault",
        "Sainte-Anne-de-Bellevue",
        "Sainte-Anne-de-Sorel",
        "Sainte-Anne-de-la-Pérade",
        "Sainte-Anne-des-Lacs",
        "Sainte-Anne-des-Monts",
        "Sainte-Anne-des-Plaines",
        "Sainte-Brigitte-de-Laval",
        "Sainte-Béatrix",
        "Sainte-Catherine",
        "Sainte-Catherine-de-Hatley",
        "Sainte-Catherine-de-la-Jacques-Cartier",
        "Sainte-Claire",
        "Sainte-Croix",
        "Sainte-Cécile-de-Masham",
        "Sainte-Dorothée",
        "Sainte-Famille",
        "Sainte-Foy",
        "Sainte-Félicité",
        "Sainte-Geneviève",
        "Sainte-Geneviève-de-Batiscan",
        "Sainte-Julie",
        "Sainte-Julienne",
        "Sainte-Luce",
        "Sainte-Lucie-des-Laurentides",
        "Sainte-Madeleine",
        "Sainte-Marguerite-du-Lac-Masson",
        "Sainte-Marguerite-du-lac-Masson",
        "Sainte-Marie",
        "Sainte-Marie-Salomé",
        "Sainte-Marie-de-Beauce",
        "Sainte-Marthe-sur-le-Lac",
        "Sainte-Martine",
        "Sainte-Mélanie",
        "Sainte-Pétronille",
        "Sainte-Rose",
        "Sainte-Sophie",
        "Sainte-Thècle",
        "Sainte-Thérèse",
        "Sainte-Thérèse-de-Gaspé",
        "Sainte-foy",
        "Sainte-Émélie-de-L'Énergie",
        "Sainte-Émélie-de-l'Énergie",
        "Saints-Anges",
        "Salaberry-de-Valleyfeild",
        "Salaberry-de-Valleyfield",
        "Sallaberry-de-Valleyfield",
        "Salluit",
        "Sant-Jean-sur-Richelieu",
        "Santé",
        "Sarre",
        "Sayabec",
        "Schefferville",
        "Senneterre",
        "Senneville",
        "Sept-Iles",
        "Sept-Îles",
        "Sept-îles",
        "Sept-ïles",
        "Shawinigan",
        "Shawinigan-Sud",
        "Shawinigan-sud",
        "Shawville",
        "Shefford",
        "Sherbrooke",
        "Shipshaw",
        "Sillery",
        "Soeurs",
        "Sorel",
        "Sorel-Tracy",
        "St-Anne-des-Monts",
        "St-Basile-le-grand",
        "St-Charles-Borromée",
        "St-Etienne-de-Lauzon",
        "St-Eustache",
        "St-Georges",
        "St-Hubert",
        "St-Hyacinthe",
        "St-Jean-Sur-Richelieu",
        "St-Jean-sur-Richelieu",
        "St-Joseph",
        "St-Jérome",
        "St-Jérôme",
        "St-Lambert",
        "St-Laurent",
        "St-Léonard-d'Aston",
        "Stanstead",
        "Ste-Anne-des-Monts",
        "Ste-Félicité",
        "Ste-Julie",
        "Ste-Thècle",
        "Stoke",
        "Stoneham",
        "Stoneham-et-Tewkesbury",
        "Sud",
        "Sutton",
        "Temiscaming",
        "Temiscouata-sur-le-Lac",
        "Terrebonne",
        "Terrobonne",
        "Terrrebonne",
        "Thetford-Mines",
        "Thurso",
        "Tracy",
        "Tring-Jonction",
        "Trois-Pistoles",
        "Trois-Rivieres",
        "Trois-Rivière",
        "Trois-Rivières",
        "Trois-rivières",
        "Tuque",
        "Témiscaming",
        "Témiscouata-sur-le-Lac",
        "Témiscouata-sur-le-lac",
        "Ulverton",
        "Upton",
        "Val-Alain",
        "Val-D'Or",
        "Val-David",
        "Val-Morin",
        "Val-d'Or",
        "Val-des-Monts",
        "Valcourt",
        "Vale",
        "Valleyfield",
        "Vallée-Jonction",
        "Varennes",
        "Vaudreuil-Dorion",
        "Venise-en-Québec",
        "Verchères",
        "Verdun",
        "Victoriaville",
        "Ville-Marie",
        "Vimont",
        "Visitation-de-L'Île-Dupas",
        "Wakefield",
        "Warwick",
        "Waskaganish",
        "Waswanipi",
        "Waterloo",
        "Waterville",
        "Weedon",
        "Wemindji",
        "Wendake",
        "Westbury",
        "Westmount",
        "Whapmagoostui",
        "Windsor",
        "Woburn",
        "Wémindji",
        "Yamachiche",
        "baie",
        "borromée",
        "chateauguay",
        "d'Arthabaska",
        "d'Auvergne",
        "d'Or",
        "hampstead",
        "l'Assomption",
        "lac",
        "laval",
        "longueuil",
        "mines",
        "montreal",
        "neiges",
        "ormstown",
        "park",
        "pointe-claire",
        "sud",
        "Éboulements",
        "Étang-du-Nord"
    ]
    
    static let britishColumbiaNames = [
        "ALL",
        "Abbotsford",
        "Agassiz",
        "Aldergrove",
        "Alert Bay",
        "Anmore",
        "Armstrong",
        "Ashcroft",
        "Barriere",
        "Belcarra",
        "Bella Bella",
        "Bella Coola",
        "Bowen Island",
        "Brentwood Bay",
        "Burnaby",
        "Burns Lake",
        "CHILLIWACK",
        "Campbell River",
        "Canoe",
        "Cassidy",
        "Castlegar",
        "Cedar",
        "Charlie Lake",
        "Chase",
        "Chemainus",
        "Chetwynd",
        "Chilliwack",
        "Christina Lake",
        "Clearwater",
        "Cobble Hill",
        "Coldstream",
        "Comox",
        "Coquitlam",
        "Courtenay",
        "Cranbrook",
        "Creston",
        "Cumberland",
        "DUNCAN",
        "Dawson Creek",
        "Dease Lake",
        "Delta",
        "Denman Island",
        "Duncan",
        "Elkford",
        "Enderby",
        "Esquimalt",
        "Fairmont Hot Springs",
        "Fanny Bay",
        "Fernie",
        "Fort Langley",
        "Fort Nelson",
        "Fort St James",
        "Fort St John",
        "Fraser Lake",
        "Fruitvale",
        "Gabriola",
        "Galiano",
        "Ganges",
        "Garden Bay",
        "Garibaldi Highlands",
        "Gibsons",
        "Gillies Bay",
        "Gold River",
        "Golden",
        "Grand Forks",
        "Greenwood",
        "Grindrod",
        "Hagensborg",
        "Halfmoon Bay",
        "Hazelton",
        "Hope",
        "Hornby Island",
        "Houston",
        "Invermere",
        "Kamloops",
        "Kaslo",
        "Kelowna",
        "Keremeos",
        "Kimberley",
        "Kitimat",
        "Ladner",
        "Ladysmith",
        "Lake Country",
        "Lake Cowichan",
        "Langley",
        "Lantzville",
        "Lazo",
        "Lillooet",
        "Lions Bay",
        "Logan Lake",
        "Lumby",
        "Lytton",
        "MacKenzie",
        "Mackenzie",
        "Mansons Landing",
        "Maple Ridge",
        "Mara",
        "Masset",
        "McBride",
        "Merritt",
        "Midway",
        "Mill Bay",
        "Mission",
        "Nakusp",
        "Nanaimo",
        "Nanoose Bay",
        "Nelson",
        "New Denver",
        "New Westminster",
        "North Delta",
        "North Saanich",
        "North Vancouver",
        "Okanagan Falls",
        "Oliver",
        "Osoyoos",
        "Parksville",
        "Peachland",
        "Pemberton",
        "Pender Island",
        "Penticton",
        "Pitt Meadows",
        "Port Alberni",
        "Port Alice",
        "Port Coquitlam",
        "Port Hardy",
        "Port McNeill",
        "Port Moody",
        "Powell River",
        "Prince George",
        "Prince Rupert",
        "Princeton",
        "Pritchard",
        "Qualicum Beach",
        "Quathiaski Cove",
        "Queen Charlotte City",
        "Queen Charlotte",
        "Quesnel",
        "RIchmond",
        "Revelstoke",
        "Richmond",
        "Roberts Creek",
        "Rock Creek",
        "Rossland",
        "Saanichton",
        "Salmo",
        "Salmon Arm",
        "Salt Spring Island",
        "Sardis",
        "Sechelt",
        "Shawnigan Lake",
        "Sicamous",
        "Sidney",
        "Slocan Park",
        "Smithers",
        "Sooke",
        "Sorrento",
        "Sparwood",
        "Squamish",
        "Stewart",
        "Summerland",
        "Sun Peaks",
        "Surrey",
        "Tatla Lake",
        "Terrace",
        "Tofino",
        "Trail",
        "Tumbler Ridge",
        "Ucluelet",
        "VANCOUVER",
        "VICTORIA",
        "Valemount",
        "Vancouver",
        "Vanderhoof",
        "Vernon",
        "Victoria",
        "Waglisla",
        "West Kelowna",
        "West Vancouver",
        "Westbank",
        "Whistler",
        "White Rock",
        "Williams Lake",
        "Wilson Creek",
        "Windermere",
        "Winfield",
        "Winlaw"
    ]
    
    static let ontarioNames = [
        "ALL",
        "Acton",
        "Addison",
        "Agincourt",
        "Ailsa Craig",
        "Ajax",
        "Akwesasne",
        "Alban",
        "Alberton",
        "Aldershot",
        "Alexandria",
        "Alfred",
        "Algoma Mills",
        "Allenford",
        "Alliston",
        "Alma",
        "Almonte",
        "Alton",
        "Alvinston",
        "Amaranth",
        "Ameliasburgh",
        "Amherst Island",
        "Amherstburg",
        "Amherstview",
        "Ancaster",
        "Angus",
        "Annan",
        "Ansonville",
        "Appin",
        "Apple Hill",
        "Apsley",
        "Arden",
        "Ardoch",
        "Ariss",
        "Arkona",
        "Armstrong",
        "Arnprior",
        "Arnstein",
        "Arthur",
        "Arva",
        "Ashburn",
        "Ashton",
        "Asphodel-Norwood",
        "Astorville",
        "Astra",
        "Athens",
        "Atikokan",
        "Attawapiskat",
        "Atwood",
        "Auburn",
        "Aurora",
        "Avonmore",
        "Aweres Township",
        "Aylmer",
        "Ayr",
        "Ayton",
        "Azilda",
        "Baden",
        "Badjeros",
        "Bailieboro",
        "Bainsville",
        "Bala",
        "Balderson",
        "Baldwin",
        "Ballainafad",
        "Balmertown",
        "Baltimore",
        "Bancroft",
        "Barrie",
        "Barriefield",
        "Barrys Bay",
        "Bath",
        "Battersea",
        "Bay Ridges",
        "Bayfield",
        "Baysville",
        "Beachburg",
        "Beachville",
        "Beamsville",
        "Bear Island",
        "Beardmore",
        "Beaverton",
        "Beeton",
        "Belfountain",
        "Belgrave",
        "Bell Ewart",
        "Belle River",
        "Belle Vallee",
        "Belleville",
        "Bells Corners",
        "Belmont",
        "Belwood",
        "Berkeley",
        "Berwick",
        "Bethany",
        "Bewdley",
        "Big Trout Lake",
        "Binbrook",
        "Blackburn Hamlet",
        "Blackstock",
        "Blenheim",
        "Blezard Valley",
        "Blind River",
        "Bloomfield",
        "Blossom Park",
        "Blue Mountains",
        "Bluevale",
        "Blyth",
        "Bobcaygeon",
        "Bognor",
        "Bolton",
        "Bond Head",
        "Bonfield",
        "Borden",
        "Bornholm",
        "Bothwell",
        "Bourget",
        "Bowmanville",
        "Bracebridge",
        "Bradford",
        "Braeside",
        "Bramalea",
        "Brampton",
        "Branchton",
        "Brantford",
        "Brechin",
        "Breslau",
        "Bridgenorth",
        "Brigden",
        "Bright",
        "Brighton",
        "Brights Grove",
        "Brinston",
        "Brockville",
        "Bronte",
        "Brooklin",
        "Brougham",
        "Brownsville",
        "Bruce Mines",
        "Brucefield",
        "Brunner",
        "Brussels",
        "Buckhorn",
        "Burford",
        "Burgessville",
        "Burks Falls",
        "Burleigh Falls",
        "Burlington",
        "Burnstown",
        "Burwash",
        "Cache Bay",
        "Caesarea",
        "Caistor Centre",
        "Calabogie",
        "Caledon",
        "Caledon East",
        "Caledon Village",
        "Caledonia",
        "Callander",
        "Calstock",
        "Cambridge",
        "Camden East",
        "Cameron",
        "Camlachie",
        "Campbellcroft",
        "Campbellford",
        "Campbellville",
        "Canfield",
        "Cannifton",
        "Cannington",
        "Capreol",
        "Caramat",
        "Cardiff",
        "Cardinal",
        "Cardinal Heights",
        "Cargill",
        "Carleton Place",
        "Carlisle",
        "Carlsbad Springs",
        "Carnarvon",
        "Carp",
        "Carrying Place",
        "Casselman",
        "Castleton",
        "Cat Lake",
        "Cavan",
        "Cavan Monaghan",
        "Cayuga",
        "Cedar Point",
        "Cedar Springs",
        "Cedar Valley",
        "Centralia",
        "Centreville",
        "Chaffeys Lock",
        "Chalk River",
        "Chapleau",
        "Charing Cross",
        "Charlton",
        "Chatham",
        "Chatsworth",
        "Chelmsford",
        "Cheltenham",
        "Chepstow",
        "Cherry Valley",
        "Chesley",
        "Chesterville",
        "Chippawa",
        "Christian Island",
        "Churchill",
        "Chute-a-blondeau",
        "Claremont",
        "Clarence Creek",
        "Clarendon",
        "Clarington",
        "Clarksburg",
        "Clarkson",
        "Clayton",
        "Clearwater",
        "Clifford",
        "Clinton",
        "Cloyne",
        "Coatsworth",
        "Cobalt",
        "Cobden",
        "Coboconk",
        "Cobourg",
        "Cochenour",
        "Cochrane",
        "Codrington",
        "Coe Hill",
        "Colborne",
        "Colchester",
        "Coldstream",
        "Coldwater",
        "Colgan",
        "Collingwood",
        "Collins Bay",
        "Comber",
        "Combermere",
        "Commanda",
        "Concord",
        "Conestogo",
        "Coniston",
        "Conn",
        "Connaught",
        "Consecon",
        "Constance Bay",
        "Cookstown",
        "Cooksville",
        "Cooper",
        "Copetown",
        "Copper Cliff",
        "Corbeil",
        "Corbyville",
        "Cornwall",
        "Corunna",
        "Cottam",
        "Courtice",
        "Courtland",
        "Courtright",
        "Craigleith",
        "Crediton",
        "Creemore",
        "Creighton Mine",
        "Croton",
        "Crysler",
        "Crystal Beach",
        "Crystal Falls",
        "Culter",
        "Cumberland",
        "Cumberland Beach",
        "Curran",
        "Curve Lake",
        "Dacre",
        "Dalkeith",
        "Dashwood",
        "Deep River",
        "Delaware",
        "Delhi",
        "Delta",
        "Demorestville",
        "Denbigh",
        "Denfield",
        "Desbarats",
        "Desboro",
        "Deseronto",
        "Devlin",
        "Dobbinton",
        "Don Mills",
        "Dorchester",
        "Dorset",
        "Douglas",
        "Douro",
        "Douro-Dummer",
        "Dover Centre",
        "Dowling",
        "Downsview",
        "Drayton",
        "Dresden",
        "Drumbo",
        "Dryden",
        "Duart",
        "Dunchurch",
        "Dundalk",
        "Dundas",
        "Dungannon",
        "Dunnville",
        "Dunrobin",
        "Dunsford",
        "Duntroon",
        "Dunvegan",
        "Durham",
        "Dutton",
        "Dwight",
        "Dymond",
        "Eagle Lake",
        "Eagle River",
        "Ear Falls",
        "Earlton",
        "East Garafraxa",
        "East Gwillimbury",
        "East York",
        "Eastview",
        "Echo Bay",
        "Eden",
        "Eden Mills",
        "Edwards",
        "Eganville",
        "Egbert",
        "Egmondville",
        "Eldee",
        "Eldorado",
        "Elgin",
        "Elginburg",
        "Elizabethtown",
        "Elizabethtown Township",
        "Elk Lake",
        "Elliot Lake",
        "Elmira",
        "Elmvale",
        "Elmwood",
        "Elora",
        "Elphin",
        "Embro",
        "Embrun",
        "Emeryville",
        "Emo",
        "Emsdale",
        "Englehart",
        "Ennismore",
        "Enterprise",
        "Erieau",
        "Erin",
        "Erinsville",
        "Espanola",
        "Essex",
        "Etobicoke",
        "Everett",
        "Exeter",
        "Falconbridge",
        "Fallbrook",
        "Fauquier",
        "Fenelon Falls",
        "Fenwick",
        "Fergus",
        "Fernleigh",
        "Feversham",
        "Field",
        "Finch",
        "Fingal",
        "Fisherville",
        "Fitzroy Harbour",
        "Flamborough",
        "Flesherton",
        "Flinton",
        "Floradale",
        "Florence",
        "Foleyet",
        "Fonthill",
        "Fordwich",
        "Forest",
        "Fort Albany",
        "Fort Erie",
        "Fort Frances",
        "Fort Hope",
        "Fort William",
        "Foxboro",
        "Foymount",
        "Frankford",
        "Fraserdale",
        "Fraserville",
        "Freelton",
        "Fruitland",
        "Fullarton",
        "Gads Hill Station",
        "Galt",
        "Gananoque",
        "Garden River",
        "Garden Village",
        "Garson",
        "Georgetown",
        "Georgina",
        "Geraldton",
        "Gilford",
        "Gilmour",
        "Glanworth",
        "Glen Huron",
        "Glen Robertson",
        "Glen Williams",
        "Glenburnie",
        "Glencairn",
        "Glencoe",
        "Gloucester",
        "Goderich",
        "Godfrey",
        "Gogama",
        "Golden Lake",
        "Golden Valley",
        "Gooderham",
        "Goodwood",
        "Gore Bay",
        "Gores Landing",
        "Gormley",
        "Gorrie",
        "Goulais River",
        "Gowanstown",
        "Grafton",
        "Grand Bend",
        "Grand Valley",
        "Grande Pointe",
        "Granton",
        "Grassie",
        "Gravenhurst",
        "Greely",
        "Green Valley",
        "Greenbank",
        "Greensville",
        "Greenwood",
        "Griffith",
        "Grimsby",
        "Guelph",
        "Gull Bay",
        "Hagersville",
        "Haileybury",
        "Haley Station",
        "Haliburton",
        "Halton Hills",
        "Hamilton",
        "Hammond",
        "Hampton",
        "Hanlan Township",
        "Hanmer",
        "Hannon",
        "Hanover",
        "Harcourt",
        "Harley",
        "Harrietsville",
        "Harriston",
        "Harrow",
        "Harrowsmith",
        "Hartington",
        "Hastings",
        "Havelock",
        "Hawk Junction",
        "Hawkesbury",
        "Hawkestone",
        "Hawkesville",
        "Hazeldean",
        "Hearst",
        "Heidelberg",
        "Hensall",
        "Hepworth",
        "Heron Bay",
        "Heron Bay South",
        "Hespeler",
        "Hickson",
        "Highgate",
        "Highland Grove",
        "Hilldale",
        "Hilliardton",
        "Hillier",
        "Hillsburgh",
        "Hilton Beach",
        "Holland Landing",
        "Holstein",
        "Holyrood",
        "Honey Harbour",
        "Hornby",
        "Hornell Heights",
        "Hornepayne",
        "Hornings Mills",
        "Hudson",
        "Huntsville",
        "Huron Park",
        "Huttonville",
        "Hyde Park",
        "Ignace",
        "Ilderton",
        "Indian River",
        "Ingersoll",
        "Ingleside",
        "Inglewood",
        "Ingolf",
        "Innerkip",
        "Innisfil",
        "Inverary",
        "Iron Bridge",
        "Irondale",
        "Iroquois",
        "Iroquois Falls",
        "Island Grove",
        "Islington",
        "Jacksons Point",
        "Jamestown",
        "Janetville",
        "Jarvis",
        "Jasper",
        "Jerseyville",
        "Johnstown",
        "Jordan",
        "Jordan Station",
        "Joyceville",
        "Kagawong",
        "Kakabeka Falls",
        "Kaladar",
        "Kaministiquia",
        "Kanata",
        "Kapuskasing",
        "Kars",
        "Katrine",
        "Kearney",
        "Keene",
        "Keewatin",
        "Kemble",
        "Kemptville",
        "Kenabeek",
        "Kendal",
        "Kenilworth",
        "Kenmore",
        "Kenora",
        "Kent Bridge",
        "Kerwood",
        "Keswick",
        "Kettleby",
        "Kilbride",
        "Killaloe",
        "Killarney",
        "Kilworth",
        "Kilworthy",
        "Kimberley",
        "Kinburn",
        "Kincardine",
        "King",
        "King City",
        "King Kirkland",
        "Kingston",
        "Kingsville",
        "Kinmount",
        "Kintore",
        "Kirkfield",
        "Kirkland Lake",
        "Kirkton",
        "Kitchener",
        "Kleinburg",
        "Komoka",
        "La Salette",
        "La Salle",
        "Lagoon City",
        "Lakefield",
        "Lakehurst",
        "Lakeshore",
        "L'Amable",
        "Lambeth",
        "Lambton Shores",
        "Lanark",
        "Lancaster",
        "Langstaff",
        "Langton",
        "Lansdowne",
        "Larder Lake",
        "Latchford",
        "Lavigne",
        "Leamington",
        "Lefroy",
        "Leith",
        "Levack",
        "Limehouse",
        "Limoges",
        "Lincoln",
        "Lindsay",
        "Linwood",
        "Lions Head",
        "Lisle",
        "Listowel",
        "Little Britain",
        "Little Current",
        "Lively",
        "Locust Hill",
        "Lombardy",
        "Londesborough",
        "London",
        "Long Sault",
        "Longbow Lake",
        "Longford  Mills",
        "Longlac",
        "Loretto",
        "L'orignal",
        "Loring",
        "Lorne Park",
        "Lowbanks",
        "Lucan",
        "Lucknow",
        "Lunenburg",
        "Lyn",
        "Lynden",
        "Lyndhurst",
        "Maberly",
        "Mactier",
        "Madawaska",
        "Madoc",
        "Madsen",
        "Magnetawan",
        "Maidstone",
        "Maitland",
        "Mallorytown",
        "Malton",
        "Manilla",
        "Manitouwadge",
        "Manitowaning",
        "Manotick",
        "Mansfield",
        "Maple",
        "Maple Leaf",
        "Marathon",
        "Markdale",
        "Markham",
        "Markstay",
        "Marlbank",
        "Marmora",
        "Martintown",
        "Maryhill",
        "Marysville",
        "Massey",
        "Matachewan",
        "Matheson",
        "Mattawa",
        "Mattice",
        "Maxville",
        "Maxwell",
        "Maynooth",
        "Mcdonald",
        "McDonalds Corners",
        "McDougall",
        "McGregor",
        "McKellar",
        "McKerrow",
        "Meadowvale",
        "Meaford",
        "Melancthon",
        "Melbourne",
        "Meldrum Bay",
        "Merlin",
        "Merrickville",
        "Merritton",
        "Metcalfe",
        "Midhurst",
        "Midland",
        "Mildmay",
        "Milford",
        "Milford Bay",
        "Millbrook",
        "Miller Lake",
        "Millgrove",
        "Milliken",
        "Milton",
        "Milverton",
        "Minaki",
        "Mindemoya",
        "Minden",
        "Minesing",
        "Minett",
        "Mississauga",
        "Mitchell",
        "Mitchell's Bay",
        "Mobert",
        "Moffat",
        "Monetville",
        "Monkland",
        "Monkton",
        "Mono",
        "Mono Mills",
        "Monteith",
        "Moonbeam",
        "Moonstone",
        "Moorefield",
        "Mooretown",
        "Moose Creek",
        "Moose Factory",
        "Moosonee",
        "Morewood",
        "Morpeth",
        "Morrisburg",
        "Morriston",
        "Moscow",
        "Mossley",
        "Mount Albert",
        "Mount Brydges",
        "Mount Elgin",
        "Mount Forest",
        "Mount Hope",
        "Mount Pleasant",
        "Mountain",
        "Mountain Grove",
        "Muirkirk",
        "Mulmur",
        "Muncey",
        "Munster",
        "Murillo",
        "Nairn Centre",
        "Nakina",
        "Nanticoke",
        "Napanee",
        "Naughton",
        "Navan",
        "Neebing",
        "Nepean",
        "Nestleton",
        "Neustadt",
        "New Dundee",
        "New Hamburg",
        "New Liskeard",
        "New Lowell",
        "Newboro",
        "Newburgh",
        "Newbury",
        "Newcastle",
        "Newington",
        "Newmarket",
        "Newtonville",
        "Niagara Falls",
        "Niagara-on-the-lake",
        "Nipigon",
        "Nipissing",
        "Nobel",
        "Nobleton",
        "Noelville",
        "Nolalu",
        "Norland",
        "North Augusta",
        "North Bay",
        "North Buxton",
        "North Cobalt",
        "North Gower",
        "North Lancaster",
        "North York",
        "Northbrook",
        "Norval",
        "Norwich",
        "Norwood",
        "Nottawa",
        "Novar",
        "Oak Ridges",
        "Oakville",
        "Oakwood",
        "Odessa",
        "Ohsweken",
        "Oil Springs",
        "Oldcastle",
        "Omemee",
        "Ompah",
        "Onaping",
        "Opasatika",
        "Orangeville",
        "Orillia",
        "Orleans",
        "Oro",
        "Oro Station",
        "Oro-Medonte",
        "Orono",
        "Orton",
        "Osgoode",
        "Oshawa",
        "Otonabee",
        "Ottawa",
        "Otterville",
        "Owen Sound",
        "Oxford Mills",
        "Oxford Station",
        "Paincourt",
        "Painswick",
        "Paisley",
        "Pakenham",
        "Palgrave",
        "Palmer Rapids",
        "Palmerston",
        "Parham",
        "Paris",
        "Parkhill",
        "Parry Sound",
        "Pefferlaw",
        "Pelee Island",
        "Pelham",
        "Pembroke",
        "Penetang",
        "Penetanguishene",
        "Perkinsfield",
        "Perth",
        "Perth Road",
        "Petawawa",
        "Peterborough",
        "Petersburg",
        "Petrolia",
        "Phelpston",
        "Pickerel",
        "Pickering",
        "Pickle Lake",
        "Picton",
        "Pikangikum",
        "Plainfield",
        "Plainville",
        "Plantagenet",
        "Plattsville",
        "Plevna",
        "Point Edward",
        "Pointe Au Baril",
        "Pointe-aux-Roches",
        "Pontypool",
        "Porcupine",
        "Porquis Junction",
        "Port Arthur",
        "Port Burwell",
        "Port Carling",
        "Port Colborne",
        "Port Credit",
        "Port Dover",
        "Port Elgin",
        "Port Franks",
        "Port Hope",
        "Port Lambton",
        "Port Loring",
        "Port McNicoll",
        "Port Perry",
        "Port Robinson",
        "Port Rowan",
        "Port Severn",
        "Port Stanley",
        "Port Sydney",
        "Portland",
        "Powassan",
        "Prescott",
        "Preston",
        "Priceville",
        "Prince Albert",
        "Prince Township",
        "Princeton",
        "Proton Station",
        "Providence Bay",
        "Puce",
        "Puslinch",
        "Putnam",
        "Queenston",
        "Queensville",
        "Rainy River",
        "Rama",
        "Ramore",
        "Ravenna",
        "Reaboro",
        "Red Lake",
        "Red Rock",
        "Redbridge",
        "Renfrew",
        "Rexdale",
        "Richards Landing",
        "Richmond",
        "Richmond Hill",
        "Rideau Ferry",
        "Ridgetown",
        "Ridgeville",
        "Ridgeway",
        "Ripley",
        "River Drive Park",
        "Riverside",
        "Roblin",
        "Rochester",
        "Rockcliffe",
        "Rockcliffe Park",
        "Rockland",
        "Rockport",
        "Rockton",
        "Rockwood",
        "Rodney",
        "Rosemont",
        "Roseneath",
        "Roslin",
        "Rosseau",
        "Rosslyn",
        "Rossmore",
        "Rossport",
        "Rostock",
        "Russell",
        "Rutherglen",
        "Ruthven",
        "Salem",
        "Sandwich West",
        "Sandy Lake",
        "Sarnia",
        "Sarsfield",
        "Sauble Beach",
        "Sault Ste Marie",
        "Savant Lake",
        "Scarborough",
        "Schomberg",
        "Schreiber",
        "Schumacher",
        "Scotland",
        "Seaforth",
        "Seagrave",
        "Sebright",
        "Sebringville",
        "Seeleys Bay",
        "Seguin",
        "Selby",
        "Selkirk",
        "Selwyn",
        "Serpent River",
        "Sesekinika",
        "Severn",
        "Severn Bridge",
        "Shakespeare",
        "Shallow Lake",
        "Shannonville",
        "Shanty Bay",
        "Sharbot Lake",
        "Sharon",
        "Shedden",
        "Sheffield",
        "Sheguiandah",
        "Shelburne",
        "Sherkston",
        "Shining Tree",
        "Shuniah",
        "Simcoe",
        "Singhampton",
        "Sioux Lookout",
        "Sioux Narrows",
        "Skead",
        "Slate Falls",
        "Smiths Falls",
        "Smithville",
        "Smooth Rock Falls",
        "Snelgrove",
        "Snow Road Station",
        "Sombra",
        "South Bay Mouth",
        "South Bruce Peninsula",
        "South Gillies",
        "South Mountain",
        "South Porcupine",
        "South River",
        "South Woodslee",
        "Southampton",
        "SouthWold",
        "Spanish",
        "Spencerville",
        "Spring Bay",
        "Springbrook",
        "Springfield",
        "Springford",
        "Sprucedale",
        "St Agatha",
        "St Albert",
        "St Andrews West",
        "St Anns",
        "St Catharines",
        "St Charles",
        "St Clair Beach",
        "St Clements",
        "St Davids",
        "St Eugene",
        "St George",
        "St George Brant",
        "St Isidore",
        "St Isidore Des Prescott",
        "St Jacobs",
        "St Joachim",
        "St Marys",
        "St Pascal Baylon",
        "St Pauls Station",
        "St Thomas",
        "St Williams",
        "Staples",
        "Stayner",
        "Stella",
        "Stevensville",
        "Stirling",
        "Stittsville",
        "Stoney Creek",
        "Stoney Point",
        "Stouffville",
        "Straffordville",
        "Stratford",
        "Strathroy",
        "Stratton",
        "Streetsville",
        "Stroud",
        "Sturgeon Falls",
        "Sudbury",
        "Sultan",
        "Summerstown",
        "Sunderland",
        "Sundridge",
        "Sutton",
        "Sutton West",
        "Swastika",
        "Sydenham",
        "Talbotville",
        "Tamworth",
        "Tara",
        "Tarzwell",
        "Tavistock",
        "Tecumseh",
        "Teeswater",
        "Temagami",
        "Terra Cotta",
        "Terrace Bay",
        "Thamesford",
        "Thamesville",
        "Thedford",
        "Thessalon",
        "Thomasburg",
        "Thornbury",
        "Thorndale",
        "Thorne",
        "Thornhill",
        "Thornton",
        "Thorold",
        "Thunder Bay",
        "Tichborne",
        "Tilbury",
        "Tillsonburg",
        "Timmins",
        "Tiny",
        "Tiverton",
        "Tobermory",
        "Toledo",
        "Toronto",
        "Torrance",
        "Tottenham",
        "Townsend",
        "Trent Lakes",
        "Trent River",
        "Trenton",
        "Trout Creek",
        "Troy",
        "Tupperville",
        "Tweed",
        "Udora",
        "Union",
        "Unionville",
        "Utopia",
        "Utterson",
        "Uxbridge",
        "Val Caron",
        "Val Gagne",
        "Val Rita",
        "Val Therese",
        "Vandorf",
        "Vanessa",
        "Vanier",
        "Vankleek Hill",
        "Vars",
        "Vaughan",
        "Vermilion Bay",
        "Verner",
        "Verona",
        "Vickers Heights",
        "Victoria Harbour",
        "Vienna",
        "Vineland",
        "Vineland Station",
        "Vinemount",
        "Virgil",
        "Virginiatown",
        "Vittoria",
        "Wabigoon",
        "Wahnapitae",
        "Wainfleet",
        "Walden",
        "Walford",
        "Walkerton",
        "Walkerville",
        "Wallace Town",
        "Wallaceburg",
        "Wallenstein",
        "Walters Falls",
        "Walton",
        "Wardsville",
        "Warkworth",
        "Warminster",
        "Warren",
        "Warsaw",
        "Wasaga Beach",
        "Washago",
        "Waterdown",
        "Waterford",
        "Waterloo",
        "Watford",
        "Waubaushene",
        "Wawa",
        "Webbwood",
        "Welland",
        "Wellandport",
        "Wellesley",
        "Wellington",
        "Wendover",
        "West Bay",
        "West Flamborough",
        "West Guilford",
        "West Hill",
        "West Lorne",
        "West Montrose",
        "Westbrook",
        "Westdale",
        "Westmeath",
        "Westminster",
        "Weston",
        "Westport",
        "Wheatley",
        "Whitby",
        "White Lake",
        "White River",
        "Whitedog",
        "Whitefish",
        "Whitefish Falls",
        "Whitefish River",
        "Whitevale",
        "Whitney",
        "Wiarton",
        "Wikwemikong",
        "Wilberforce",
        "Wilkesport",
        "Williamsburg",
        "Williamsford",
        "Williamstown",
        "Willow Beach",
        "Willowdale",
        "Wilno",
        "Wilsonville",
        "Winchester",
        "Windermere",
        "Windham Centre",
        "Windsor",
        "Wingham",
        "Winona",
        "Wolfe Island",
        "Woodbridge",
        "Woodham",
        "Woodland Beach",
        "Woodlawn",
        "Woodslee",
        "Woodstock",
        "Woodview",
        "Woodville",
        "Wooler",
        "Worthington",
        "Wroxeter",
        "Wyebridge",
        "Wyevale",
        "Wyoming",
        "Yarker",
        "York",
        "Zephyr",
        "Zurich"
    ]
    
}