//
//  Hospital.swift
//  DoctorNearby
//
//  Created by Vince Zhang on 2015-09-25.
//  Copyright © 2015 AkhalTech. All rights reserved.
//

import Foundation

class Hospital: NSObject {
    class func names() -> Array <String> {
        return [
            "ALL",
            "Alexandra Hospital",
            "Alexandra Marine and General Hospital",
            "Almonte General Hospital",
            "Anson General Hospital",
            "Arnprior and District Memorial Hospital",
            "Atikokan General Hospital",
            "Baycrest Hospital",
            "Beechwood Private Hospital",
            "Bellwood Health Services Inc.",
            "Bingham Memorial Hospital",
            "Blind River District Health Centre",
            "Bluewater Health Sarnia General Hospital",
            "Bluewater Health,Charlotte Eleanor Englehart Site",
            "Brant Community Healthcare System",
            "Brant Community Healthcare System,Willett Site",
            "Brentwood Recovery Home",
            "Bridgepoint Hospital",
            "Brockville General Hospital",
            "Brockville General Hospital",
            "Bruyere Continuing Care-Elisabeth Bruyere Site",
            "Bruyere Continuing Care-St Vincent Hospital Site",
            "Cambridge Memorial Hospital",
            "Campbellford Memorial Hospital",
            "Carleton Place &amp; District Memorial Hospital",
            "Casey House Hospice",
            "Centre for Addiction &amp; Mental Health,- Russell Street Site",
            "Centre for Addiction &amp; Mental Health,Queen Street Site",
            "Centre of Addiction &amp; Mental Health,- College Street Site",
            "Chapleau Health Services,Chapleau General Hospital",
            "Chatham Public General Hospital Society",
            "Chatham-Kent Health Alliance",
            "Children's Hospital of Eastern Ontario,Eastern Ontario",
            "Clinton Public Hospital",
            "Collingwood General and Marine Hospital",
            "Cornwall Community Hospital",
            "Cornwall General Hospital",
            "Deep River and District Hospital",
            "Don Mills Surgical Unit Limited",
            "Drumheller Health Centre",
            "Dryden Regional Health Centre",
            "Emo Site-Riverside Health Care Facilities",
            "Englehart and District Hospital",
            "Espanola General Hospital",
            "Four Counties Health Services,Newbury",
            "Georgian Bay General Hospital",
            "Georgian Bay General Hospital,Penetanguishene Site",
            "Geraldton District Hospital",
            "Glengarry Memorial Hospital",
            "Grand River Hospital Corporation,Freeport Site",
            "Grand River Hospital Corporation,Kitchener Waterloo Site",
            "Grey Bruce Health Services,Lions Head Site",
            "Grey Bruce Health Services,Markdale Site",
            "Grey Bruce Health Services,Meaford Site",
            "Grey Bruce Health Services,Owen Sound",
            "Grey Bruce Health Services,Southampton Hospital",
            "Grey Bruce Health Services,Wiarton Site",
            "Groves Memorial Community Hospital,Fergus",
            "Guelph General Hospital",
            "Haldimand War Memorial Hospital",
            "Haliburton Highlands Health Services,Haliburton Site",
            "Haliburton Highlands Health Services,Minden Hospital Site",
            "Halton Healthcare Services Corporation,Georgetown Hospital",
            "Hamilton Health Sciences Centre McMaster &amp; Childrens Hosp,McMaster &amp; Children's Hospital",
            "Hamilton Health Sciences Centre,Regional Rehabilitation Centre",
            "Hamilton Health Sciences Corporation,St. Peter's Hospital",
            "Hamilton Health Sciences,Chedoke Hospital Site",
            "Hamilton Health Sciences,General Site",
            "Hamilton Health Sciences,Juravinski Hospital and Cancer Centre",
            "Hanover and District Hospital",
            "Hawkesbury &amp; District General Hospital",
            "Headwaters Health Care Centre,Orangeville-Dufferin Site",
            "Health Sciences North",
            "Holland Bloorview Kids Rehabilitation Hospital",
            "Homewood Health Centre",
            "Hornepayne Community Hospital",
            "Hospice Cornwall",
            "Hospital For Sick Children",
            "Hotel Dieu Grace Healthcare,Tayfour Campus",
            "Hotel Dieu Hospital",
            "Hotel Dieu Hospital,Religious Hospitallers of St Joseph, Cornwall",
            "Hotel-Dieu-Shaver Health and Rehabilitation Centre",
            "Humber River Regional Hospital,Humber Memorial-Church Street Site",
            "Humber River Regional Hospital,Northwestern General Keele Street Site",
            "Humber River Regional Hospital,York-Finch General Finch Avenue Site",
            "Jewish General Hospital",
            "Joseph Brant Hospital",
            "Just for Kids Clinic,St. Joseph's Health Centre",
            "Kemptville District Hospital",
            "Kensington Eye Institute",
            "Kincardine and District Site,South Bruce Grey Health",
            "Kingston General Hospital",
            "Kirkland and District Hospital",
            "La Verendrye Hospital,Riverside Health Care Facilities",
            "Lady Dunn Health Centre",
            "Lady Minto Hospital",
            "Lake of the Woods District Hospital",
            "Lakeridge Health Scugog Port Perry Site",
            "Lakeridge Health,Clarington Site",
            "Lakeridge Health,Oshawa General Site",
            "Lakeridge Health,Whitby Site",
            "Leamington District Memorial Hospital",
            "Lennox and Addington County General Hospital",
            "Listowel Memorial Hospital",
            "London Health Sciences Centre South Street Hospital",
            "London Health Sciences Centre Victoria Hospital",
            "London Health Sciences Centre,Children's Hospital of Western Ontario",
            "London Health Sciences Centre,University Site",
            "Louise Marshall Hospital,North Wellington Health Care",
            "Mackenzie Health,Richmond Hill",
            "Manitoulin Health Centre",
            "Manitoulin Health Centre,Mindemoya Site",
            "Manitouwadge General Hospital",
            "Markham Stouffville Hospital",
            "Markham-Stouffville,Cottage Hospital Site",
            "Mattawa General Hospital",
            "McCausland Hospital",
            "McMaster Children's Hospital,Division of Pediatric Critical Care",
            "Mental Health Services Providence Care",
            "Milton Site Halton Healthcare Services",
            "Montfort Hospital",
            "Mount Sinai Hospital",
            "Muskoka Algonquin Health Care,South Muskoka Memorial Site",
            "Muskoka Algonquin Healthcare,Huntsville District Memorial Hospital",
            "Niagara Health System Greater Niagara Site",
            "Niagara Health System Ontario Street Site",
            "Niagara Health System Port Colborne General Site",
            "Niagara Health System,Douglas Memorial Site",
            "Niagara Health System,St Catharines General Site",
            "Niagara Health System,Welland County General Site",
            "Niagara-on-the-Lake Hospital Site,of the Niagara Health System",
            "Nipigon District Memorial Hospital",
            "Norfolk General Hospital",
            "North Bay General Hospital,Civic Site",
            "North Bay Regional Health Centre",
            "North Bay Regional Health Centre - Kirkwood Place",
            "North York General Hospital,Branson Hospital Site",
            "North York General Hospital,General Division",
            "Northumberland Hills Hospital,Cobourg District General Site",
            "Notre-Dame Hospital",
            "Oakville Trafalgar Site,Halton Healthcare Services",
            "Ontario Shores Centre for Mental Health Sciences",
            "Orillia Soldiers Memorial Hospital",
            "Ottawa Hospital,Civic Site",
            "Ottawa Hospital,General Site",
            "Ottawa Hospital,Rehabilitation Centre",
            "Ottawa Hospital,Riverside Site",
            "Ottawa National Defence Centre",
            "Palmerston &amp; District Site,North Wellington Health Care Corp",
            "Pembroke Regional Hospital",
            "Perth and Smiths Falls District Hospital,Great War Memorial Site-Perth",
            "Perth and Smiths Falls District Hospital,Smiths Falls Community Site",
            "Peterborough Regional Health Centre",
            "Providence Care Centre-St Mary's of the Lake Hospital",
            "Providence Health Care,Toronto",
            "Qikiqtani General Hospital",
            "Queensway Carleton Hospital",
            "Quinte Health Care,Trenton Memorial",
            "Quinte Healthcare North Hastings,Bancroft",
            "Quinte Healthcare Prince Edward Site",
            "Quinte Healthcare,Belleville General Site",
            "Rainy River Site-Riverside Health Care Facilities",
            "Red Lake Margaret Cochenour Memorial Hospital",
            "Renfrew Victoria Hospital",
            "Ross Memorial Hospital",
            "Rouge Valley Centenary Health Centre,Toronto",
            "Rouge Valley,Ajax and Pickering Site",
            "Royal Ottawa Health Care Group",
            "Royal Ottawa Health Care Group,Brockville Mental Health Centre",
            "Royal Victoria Regional Health Centre",
            "Runnymede Healthcare Centre",
            "Salvation Army Toronto Grace Hospital",
            "Sault Area Hospital,General/Plummer",
            "Sault Area Hospital,Sexual Assault/Partner Assault Care Centre",
            "Sault Area Hospitals,Richard's Landing Site",
            "Sault Area Hospitals,Thessalon Site",
            "Scarborough Hospital,General Site",
            "Scarborough Hospital-Birchmount Campus",
            "Seaforth Community Hospital",
            "Sensenbrenner Hospital",
            "Shelburne District Hospital,Headwaters Health Care Centre",
            "Shouldice Hospital Ltd.",
            "Sioux Lookout Zone Hospital",
            "Sioux Lookout,Meno-Ya-Win Health Centre",
            "Smooth Rock Falls Hospital",
            "South Bruce Grey Health Centre,Chesley Site",
            "South Bruce Grey Health Centre,Durham-Memorial Site",
            "South Bruce Grey Health Centre,Walkerton Site",
            "South Huron Hospital",
            "Southlake Regional Health Centre",
            "St Francis Memorial Hospital",
            "St John's Rehabilitation Hospital",
            "St Joseph Health Care,London- Mental Health",
            "St Joseph's Care Group,Lakehead Psychiatric Hospital",
            "St Joseph's Care Group,Thunder Bay",
            "St Joseph's Centre for Mountain Health Services",
            "St Joseph's Continuing Care Centre,Sudbury",
            "St Joseph's General Hospital,Elliot Lake",
            "St Joseph's Health Care,London - Parkwood Hospital",
            "St Joseph's Health Care,St Thomas Mental Health Site",
            "St Joseph's Health Care-St Joseph's Site,London",
            "St Joseph's Health Centre,Guelph",
            "St Joseph's Health Centre,Mississauga",
            "St Joseph's Health Centre,Toronto",
            "St Joseph's Health Services,Chatham-Kent Health Alliance",
            "St Joseph's Healthcare System,Hamilton",
            "St Joseph's Infirmary,Toronto",
            "St Mary's General Hospital,Kitchener",
            "St Mary's Memorial Hospital",
            "St Michael's Hospital",
            "St Thomas-Elgin General Hospital",
            "St Vincent de Paul Hospital,Providence Continuing Care Centre",
            "Stevenson Memorial Hospital",
            "Stratford General Hospital",
            "Strathroy Middlesex General Hospital",
            "Sunnybrook Health Sciences Centre",
            "Sunnybrook Health Sciences Centre,Holland Orthopaedic &amp; Arthritic Centre",
            "Sydenham District Hospital",
            "Temiskaming Hospital",
            "Thunder Bay Regional Health Sciences Centre",
            "Tillsonburg District Memorial Hospital",
            "Timmins and District General Hospital",
            "Toronto East General Hospital",
            "Trillium Health Partners,Mississauga Hospital",
            "Trillium Health Partners,Queensway Health Centre",
            "Trillium Health Partners,The Credit Valley Hospital",
            "University Health Network,E.W. Bickle Centre for Complex Continuing Care",
            "University Health Network,Hillcrest Centre",
            "University Health Network,Lyndhurst Centre",
            "University Health Network,Princess Margaret Hospital-Ontario Cancer Institute",
            "University Health Network,Rumsey Centre",
            "University Health Network,Toronto General Hospital Site",
            "University Health Network,Toronto Rehabilitation Institute",
            "University Health Network,Toronto Western Hospital Site",
            "Vaughan Cosmetic Surgery",
            "Waypoint Centre for Mental Health Care",
            "Weeneebayko Area Health Authority,Moose Factory Site",
            "Weeneebayko Health Ahtuskaywin Attawapiskat Site",
            "Weeneebayko Health Ahtuskaywin Fort Albany Site",
            "Weeneebayko Health Ahtuskaywin Moosonee Site",
            "West Haldimand,General Hospital",
            "West Lincoln Memorial Hospital",
            "West Nipissing General Hospital",
            "West Park Healthcare Centre",
            "West Parry Sound Health Centre",
            "William Osler Health Centre Etobicoke General Site",
            "William Osler Health Centre-Brampton Civic Hospital",
            "Wilson Memorial General Hospital",
            "Winchester District Memorial Hospital",
            "Windsor Regional Cancer Centre",
            "Windsor Regional Hospital,Metropolitan Site",
            "Windsor Regional Hospital,Ouellette Campus",
            "Wingham and District Hospital",
            "Women's College Hospital",
            "Woodstock General Hospital",
            "Woodstock Private Hospital"
        ]
    }
}