//
//  Specialist.swift
//  DoctorNearby
//
//  Created by Vince Zhang on 2015-09-25.
//  Copyright © 2015 AkhalTech. All rights reserved.
//

import Foundation

class Specialist: NSObject {
    class func names() -> Array <String> {
        return [
            "Adolescent Medicine",
            "Anatomical Pathology",
            "Anesthesiology",
            "Bacteriology",
            "Cardiac Surgery",
            "Cardiology",
            "Cardiothoracic Surgery",
            "Cardiovascular and Thoracic Surgery",
            "Child and Adolescent Psychiatry",
            "Clinical Immunology",
            "Clinical Immunology and Allergy",
            "Clinical Pharmacology",
            "Clinical Pharmacology and Toxicology",
            "Colorectal Surgery",
            "Community Medicine",
            "Critical Care Medicine",
            "Dermatology",
            "Developmental Paediatrics",
            "Diagnostic and Therapeutic Radiology",
            "Diagnostic Radiology",
            "Emergency Medicine",
            "Endocrinology and Metabolism",
            "Family Medicine",
            "Family Medicine (Emergency Medicine)",
            "FCFP - Family Medicine",
            "Forensic Pathology",
            "Forensic Psychiatry",
            "Gastroenterology",
            "General Internal Medicine",
            "General Pathology",
            "General Surgery",
            "General Surgical Oncology",
            "Geriatric Medicine",
            "Geriatric Psychiatry",
            "Gynecologic Oncology",
            "Gynecologic Reproductive Endocrinology & Infertility",
            "Hematological Pathology",
            "Hematology",
            "Infectious Diseases",
            "Internal Medicine",
            "Laboratory Medicine",
            "Maternal Fetal Medicine",
            "Medical Biochemistry",
            "Medical Genetics",
            "Medical Microbiology",
            "Medical Oncology",
            "Neonatal-Perinatal Medicine",
            "Nephrology",
            "Neurology",
            "Neurology and Psychiatry",
            "Neuropathology",
            "Neuroradiology",
            "Neurosurgery",
            "Nuclear Medicine",
            "Obstetrics",
            "Obstetrics and Gynecology",
            "Occupational Medicine",
            "Ophthalmology",
            "Orthopedic Surgery",
            "Otolaryngology - Head and Neck Surgery",
            "Paediatric Cardiology",
            "Paediatric Emergency Medicine",
            "Paediatric Haematology/Oncology",
            "Paediatric Radiology",
            "Paediatric Surgery",
            "Pain Medicine",
            "Pathology and Bacteriology",
            "Pediatric General Surgery",
            "Pediatrics",
            "Physical Medicine and Rehabilitation",
            "Plastic Surgery",
            "Psychiatry",
            "Public Health",
            "Public Health &amp; Preventive Medicine",
            "Radiation Oncology",
            "Respirology",
            "Rheumatology",
            "Thoracic Surgery",
            "Transfusion Medicine",
            "Urology",
            "Vascular Surgery"
        ]
    }
}